# Generated by Django 5.2.4 on 2025-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('cabinet', 'Cabinet'), ('decor', 'Decor'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
