# Generated by Django 5.2.4 on 2025-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_category_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('hall', 'Hall'), ('kitchen', 'Kitchen'), ('tvunit', 'TvUnit'), ('sofa', 'Sofa'), ('centertable', 'CenterTable'), ('bed', 'Bed'), ('cupboard', 'CupBoard'), ('door', 'Door'), ('others', 'Others')], default='other', max_length=50),
        ),
    ]
